<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-UCE2Q720" name="practico7.SoftAsserts" tests="1" failures="1" timestamp="2021-04-04T20:18:02 CEST" time="0.014" errors="0">
  <testcase name="TestAsserts" time="0.014" classname="practico7.SoftAsserts">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Error: 1 es menor que 5 expected [false] but found [true],
	Error: 10 no es mayor que 12 expected [true] but found [false],
	Error: No se obtuvo Mundo expected [Mundo] but found [Hola],
	Error: No se esperaba Hola pero obtuvo Hola did not expect [Hola] but found [Hola],
	Error: No e encuentro la letra x dentro de la palabra Hola expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Error: 1 es menor que 5 expected [false] but found [true],
Error: 10 no es mayor que 12 expected [true] but found [false],
Error: No se obtuvo Mundo expected [Mundo] but found [Hola],
Error: No se esperaba Hola pero obtuvo Hola did not expect [Hola] but found [Hola],
Error: No e encuentro la letra x dentro de la palabra Hola expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at practico7.SoftAsserts.TestAsserts(SoftAsserts.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestAsserts -->
  <system-out/>
</testsuite> <!-- practico7.SoftAsserts -->
